"""initial schema: nine tables, pgvector, HNSW, functional unique indexes

Revision ID: 0001_initial
Revises:
Create Date: 2026-06-20

Hand-written (not autogenerated) because this migration must do several things
autogenerate handles poorly: create the pgvector extension before any vector
column, create native enum types, build functional unique indexes
(lower(email); lower(first)+lower(last)+dob), add the circular
encounters.current_note_version_id FK via ALTER, and create the HNSW index.
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects import postgresql

revision: str = "0001_initial"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Enum type objects (created explicitly; columns reference them with create_type=False)
role_enum = postgresql.ENUM("provider", "admin", name="role_enum")
encounter_status = postgresql.ENUM("draft", "finalized", name="encounter_status")
diagnosis_source = postgresql.ENUM("ai_suggested", "provider_added", name="diagnosis_source")
template_status = postgresql.ENUM("active", "archived", name="template_status")

TS = sa.DateTime(timezone=True)
NOW = sa.text("now()")
UUID_DEFAULT = sa.text("gen_random_uuid()")


def _id() -> sa.Column:
    return sa.Column("id", sa.BigInteger, sa.Identity(), primary_key=True)


def upgrade() -> None:
    bind = op.get_bind()

    # pgvector extension must exist before the vector column is created.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    for e in (role_enum, encounter_status, diagnosis_source, template_status):
        e.create(bind, checkfirst=True)

    # --- providers ---
    op.create_table(
        "providers",
        _id(),
        sa.Column("email", sa.Text, nullable=False),
        sa.Column("password_hash", sa.Text, nullable=False),
        sa.Column(
            "role",
            postgresql.ENUM(name="role_enum", create_type=False),
            nullable=False,
            server_default="provider",
        ),
        sa.Column("active", sa.Boolean, nullable=False, server_default=sa.text("true")),
        sa.Column("created_at", TS, nullable=False, server_default=NOW),
        sa.Column("updated_at", TS, nullable=False, server_default=NOW),
    )
    # Case-insensitive uniqueness on email.
    op.execute("CREATE UNIQUE INDEX uq_providers_email_lower ON providers (lower(email))")

    # --- patients ---
    op.create_table(
        "patients",
        _id(),
        sa.Column("public_id", postgresql.UUID(as_uuid=True), nullable=False, server_default=UUID_DEFAULT),
        sa.Column("first_name", sa.Text, nullable=False),
        sa.Column("last_name", sa.Text, nullable=False),
        sa.Column("dob", sa.Date, nullable=False),
        sa.Column("created_at", TS, nullable=False, server_default=NOW),
        sa.Column("updated_at", TS, nullable=False, server_default=NOW),
    )
    # Spec-mandated patient identity match. PRODUCTION-UNSAFE (name+DOB collisions);
    # documented in the model. A real system would key on MRN.
    op.execute(
        "CREATE UNIQUE INDEX uq_patients_identity "
        "ON patients (lower(first_name), lower(last_name), dob)"
    )

    # --- templates ---
    op.create_table(
        "templates",
        _id(),
        sa.Column("name", sa.Text, nullable=False),
        sa.Column("encounter_type", sa.Text, nullable=False),
        sa.Column("system_prompt", sa.Text, nullable=False),
        sa.Column(
            "status",
            postgresql.ENUM(name="template_status", create_type=False),
            nullable=False,
            server_default="active",
        ),
        sa.Column("created_by", sa.BigInteger, sa.ForeignKey("providers.id"), nullable=False),
        sa.Column("created_at", TS, nullable=False, server_default=NOW),
        sa.Column("updated_at", TS, nullable=False, server_default=NOW),
    )

    # --- icd10_codes ---
    op.create_table(
        "icd10_codes",
        _id(),
        sa.Column("code", sa.Text, nullable=False, unique=True),
        sa.Column("description", sa.Text, nullable=False),
        sa.Column("embedding", Vector(384), nullable=False),
        sa.Column("embedding_model", sa.Text, nullable=False),
    )
    # HNSW index for cosine similarity nearest-neighbour search.
    op.execute(
        "CREATE INDEX ix_icd10_embedding_hnsw ON icd10_codes "
        "USING hnsw (embedding vector_cosine_ops)"
    )

    # --- encounters (current_note_version_id FK added after note_versions exists) ---
    op.create_table(
        "encounters",
        _id(),
        sa.Column("public_id", postgresql.UUID(as_uuid=True), nullable=False, server_default=UUID_DEFAULT),
        sa.Column("patient_id", sa.BigInteger, sa.ForeignKey("patients.id"), nullable=False),
        sa.Column("provider_id", sa.BigInteger, sa.ForeignKey("providers.id"), nullable=False),
        sa.Column("template_id", sa.BigInteger, sa.ForeignKey("templates.id"), nullable=True),
        sa.Column(
            "status",
            postgresql.ENUM(name="encounter_status", create_type=False),
            nullable=False,
            server_default="draft",
        ),
        sa.Column("transcript", sa.Text, nullable=True),
        sa.Column("working_note", postgresql.JSONB, nullable=True),
        sa.Column("current_note_version_id", sa.BigInteger, nullable=True),
        sa.Column("created_at", TS, nullable=False, server_default=NOW),
        sa.Column("updated_at", TS, nullable=False, server_default=NOW),
    )
    op.execute(
        "CREATE INDEX ix_encounters_provider_created "
        "ON encounters (provider_id, created_at DESC)"
    )
    op.execute(
        "CREATE INDEX ix_encounters_patient_created "
        "ON encounters (patient_id, created_at DESC)"
    )

    # --- note_versions ---
    op.create_table(
        "note_versions",
        _id(),
        sa.Column("encounter_id", sa.BigInteger, sa.ForeignKey("encounters.id"), nullable=False),
        sa.Column("version_no", sa.Integer, nullable=False),
        sa.Column("subjective", sa.Text, nullable=False, server_default=""),
        sa.Column("objective", sa.Text, nullable=False, server_default=""),
        sa.Column("assessment", sa.Text, nullable=False, server_default=""),
        sa.Column("plan", sa.Text, nullable=False, server_default=""),
        sa.Column("model_name", sa.Text, nullable=True),
        sa.Column("system_prompt_snapshot", sa.Text, nullable=True),
        sa.Column("created_by", sa.BigInteger, sa.ForeignKey("providers.id"), nullable=False),
        sa.Column("created_at", TS, nullable=False, server_default=NOW),
        sa.UniqueConstraint("encounter_id", "version_no", name="uq_note_versions_enc_verno"),
    )

    # Circular FK: latest-version pointer, added now that note_versions exists.
    op.create_foreign_key(
        "fk_enc_current_version",
        "encounters",
        "note_versions",
        ["current_note_version_id"],
        ["id"],
    )

    # --- note_version_diagnoses ---
    op.create_table(
        "note_version_diagnoses",
        _id(),
        sa.Column("note_version_id", sa.BigInteger, sa.ForeignKey("note_versions.id"), nullable=False),
        sa.Column("icd10_code_id", sa.BigInteger, sa.ForeignKey("icd10_codes.id"), nullable=False),
        sa.Column("is_primary", sa.Boolean, nullable=False, server_default=sa.text("false")),
        sa.Column(
            "source",
            postgresql.ENUM(name="diagnosis_source", create_type=False),
            nullable=False,
        ),
        sa.Column("created_at", TS, nullable=False, server_default=NOW),
    )
    op.create_index("ix_nvd_version", "note_version_diagnoses", ["note_version_id"])
    op.create_index("ix_nvd_code", "note_version_diagnoses", ["icd10_code_id"])

    # --- sessions ---
    op.create_table(
        "sessions",
        _id(),
        sa.Column("provider_id", sa.BigInteger, sa.ForeignKey("providers.id"), nullable=False),
        sa.Column("token_hash", sa.Text, nullable=False, unique=True),
        sa.Column("created_at", TS, nullable=False, server_default=NOW),
        sa.Column("expires_at", TS, nullable=False),
        sa.Column("last_seen_at", TS, nullable=True),
        sa.Column("revoked_at", TS, nullable=True),
        sa.Column("ip", sa.Text, nullable=True),
        sa.Column("user_agent", sa.Text, nullable=True),
    )
    op.create_index("ix_sessions_provider", "sessions", ["provider_id"])
    op.create_index("ix_sessions_expires", "sessions", ["expires_at"])

    # --- audit_log ---
    op.create_table(
        "audit_log",
        _id(),
        sa.Column("actor_provider_id", sa.BigInteger, sa.ForeignKey("providers.id"), nullable=False),
        sa.Column("action", sa.Text, nullable=False),
        sa.Column("entity_type", sa.Text, nullable=False),
        sa.Column("entity_id", sa.BigInteger, nullable=True),
        sa.Column("metadata", postgresql.JSONB, nullable=True),
        sa.Column("created_at", TS, nullable=False, server_default=NOW),
    )
    op.create_index("ix_audit_entity", "audit_log", ["entity_type", "entity_id"])
    op.create_index("ix_audit_actor_created", "audit_log", ["actor_provider_id", "created_at"])


def downgrade() -> None:
    bind = op.get_bind()
    op.drop_table("audit_log")
    op.drop_table("sessions")
    op.drop_table("note_version_diagnoses")
    op.drop_constraint("fk_enc_current_version", "encounters", type_="foreignkey")
    op.drop_table("note_versions")
    op.drop_table("encounters")
    op.execute("DROP INDEX IF EXISTS ix_icd10_embedding_hnsw")
    op.drop_table("icd10_codes")
    op.drop_table("templates")
    op.drop_table("patients")
    op.drop_table("providers")
    for e in (template_status, diagnosis_source, encounter_status, role_enum):
        e.drop(bind, checkfirst=True)
    op.execute("DROP EXTENSION IF EXISTS vector")
